inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - db/schema.rb
    - vendor/bundle/**/*

Style/Documentation:
  Exclude:
    - db/migrate/*

Metrics/BlockLength:
  Exclude:
    - config/routes.rb
    - spec/**/*

Metrics/MethodLength:
  Exclude:
    - db/migrate/*

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true
