version: '3'

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - RAILS_LOG_TO_STDOUT=true
      - DATABASE_NAME=workflow-server
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=sekret
      - DATABASE_HOSTNAME=db
      - DATABASE_PORT=5432
      - SECRET_KEY_BASE="${SECRET_KEY_BASE}"
#      - RAILS_ENV=development
      - SETTINGS__ENABLE_STOMP=false
      - SETTINGS__REDIS__HOSTNAME=redis
#    image: 'suldlss/workflow-server:latest-dev'
    volumes:
       - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - wfs
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=sekret
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - wfs
  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - wfs
networks:
  wfs:
