dor_services:
  url: 'http://localhost:3003'
  username: 'user'
  password: 'password'

enable_stomp: true
enable_queuing: true

messaging:
  uri: 'failover:(stomp+ssl://localhost:61612,stomp://remotehost:61613)'
  # fedora_url is sent inside the message as the `entry.author.uri` field
  fedora_url: 'https://dor-test.stanford.edu'

redis:
  url: localhost:6379
