dor_services:
  url: 'http://localhost:3003'
  username: 'user'
  password: 'password'

enable_stomp: true

messaging:
  uri: 'failover:(stomp+ssl://localhost:61612,stomp://remotehost:61613)'
  # fedora_url is sent inside the message as the `entry.author.uri` field
  fedora_url: 'https://dor-test.stanford.edu'


redis:
  hostname: localhost
  port: 6379
  db: 0
  namespace: 'resque:development'
